### PR TITLE
js additions, methods, consts, variables

### PR DESCRIPTION
**Pull request by mashaal**
added a couple more fun js emojis.

image

### CODE REVIEW

**Comment by morkro** [comment]
Awesome, thanks for your work! :tada: Looks all good so far.
Can you update your PR to my feedback?

**Comment by mashaal** [comment]
sorry about the semicolons -- been using standardjs formatting recently http://standardjs.com/

**Comment by morkro** [comment]
Cool! Version `0.5.0` is published :fire:

**Comment by mashaal** [comment]
thanks!

after some real world usage, i realize the crystal ball looks better (less annoying) as an 'after' -- i know you can update in the local settings, but would probalby be best as a default down the road. ️🐳

**Comment by morkro** [comment]
Sure, I am open for that. Can add this in a later patch update. 
Though, I am not sure if this could confuse users who already use the default option. Might have to keep the previous default state as a local setting then.

**Pull request merged**
