### PR TITLE
Javascript `const` selector update

### PR DESCRIPTION
**Pull request by dfrankland**
Caused by:
https://github.com/atom/language-javascript/commit/2445663dfb9ef43ba1998
a45a8e0dd241c70c21d
https://github.com/atom/language-javascript/commit/c63453662370c97110103
95b7bd21d7a4c8957f7

### CODE REVIEW

**Comment by morkro** [comment]
Thanks for the pull request! 

I've seen that `const` seems to be buggy at the moment. In some cases it is correctly applied, in others not. This is how the selectors look like for me on Atom `1.13.0`; I don't see the `storage.type.const.js` selector. Which version are you using?

screen shot 2017-01-24 at 22 58 11

**Comment by dfrankland** [comment]
No problem 👍 

I am also using Atom `1.13.0`. This pull-request is a bit preemptive. The next version of Atom that includes `language-javacript@>=0.125.1` will need this fix. You can test now by installing `language-javascript@0.125.1` like so:
```bash
apm install language-javascript@0.125.1
```

After you'll see the DOM like so:
screen shot 2017-01-24 at 2 24 40 pm

**Comment by morkro** [comment]
Ah, that make sense!
Great, I will merge your pull request as soon as the next Atom version is out ✌🏼

**Comment by dfrankland** [comment]
@morkro, this change is now released! https://github.com/atom/atom/releases/tag/v1.14.0

**Comment by morkro** [comment]
🙌🏻 Nice, thanks for the update!

**Pull request merged**
